spring:
  application:
    name: order-service
  datasource:
    url: ${ORDER_DB_URL:jdbc:postgresql://localhost:5432/order}
    username: ${ORDER_DB_USERNAME:order}
    password: ${ORDER_DB_PASSWORD:order}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: ${SERVER_PORT:8083}
